// This file was generated by Mendix Modeler 7.23.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tbncommon.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the TBNCommon module
	public static tbncommon.proxies.Metadata dS_Metadata(IContext context)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			IMendixObject result = (IMendixObject)Core.execute(context, "TBNCommon.DS_Metadata", params);
			return result == null ? null : tbncommon.proxies.Metadata.initialize(context, result);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String numberString(IContext context, java.lang.Long _pointer, java.lang.String _amountUnit, java.lang.Long _length, java.lang.Long _resultMod)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("pointer", _pointer);
			params.put("AmountUnit", _amountUnit);
			params.put("Length", _length);
			params.put("ResultMod", _resultMod);
			return (java.lang.String)Core.execute(context, "TBNCommon.NumberString", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
	public static java.lang.String translateAmount(IContext context, java.lang.String _amountUnit)
	{
		try
		{
			Map<java.lang.String, Object> params = new HashMap<java.lang.String, Object>();
			params.put("AmountUnit", _amountUnit);
			return (java.lang.String)Core.execute(context, "TBNCommon.TranslateAmount", params);
		}
		catch (CoreException e)
		{
			throw new MendixRuntimeException(e);
		}
	}
}