// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package tbncommon.proxies;

public class Metadata
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject metadataMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "TBNCommon.Metadata";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RuntimeVersion("RuntimeVersion"),
		ProjectID("ProjectID"),
		ProjectName("ProjectName"),
		ModelVersion("ModelVersion"),
		Description("Description"),
		AdminUser("AdminUser");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Metadata(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "TBNCommon.Metadata"));
	}

	protected Metadata(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject metadataMendixObject)
	{
		if (metadataMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("TBNCommon.Metadata", metadataMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a TBNCommon.Metadata");

		this.metadataMendixObject = metadataMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Metadata.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static tbncommon.proxies.Metadata initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return tbncommon.proxies.Metadata.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static tbncommon.proxies.Metadata initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new tbncommon.proxies.Metadata(context, mendixObject);
	}

	public static tbncommon.proxies.Metadata load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return tbncommon.proxies.Metadata.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of RuntimeVersion
	 */
	public final java.lang.String getRuntimeVersion()
	{
		return getRuntimeVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of RuntimeVersion
	 */
	public final java.lang.String getRuntimeVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RuntimeVersion.toString());
	}

	/**
	 * Set value of RuntimeVersion
	 * @param runtimeversion
	 */
	public final void setRuntimeVersion(java.lang.String runtimeversion)
	{
		setRuntimeVersion(getContext(), runtimeversion);
	}

	/**
	 * Set value of RuntimeVersion
	 * @param context
	 * @param runtimeversion
	 */
	public final void setRuntimeVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String runtimeversion)
	{
		getMendixObject().setValue(context, MemberNames.RuntimeVersion.toString(), runtimeversion);
	}

	/**
	 * @return value of ProjectID
	 */
	public final java.lang.String getProjectID()
	{
		return getProjectID(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectID
	 */
	public final java.lang.String getProjectID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProjectID.toString());
	}

	/**
	 * Set value of ProjectID
	 * @param projectid
	 */
	public final void setProjectID(java.lang.String projectid)
	{
		setProjectID(getContext(), projectid);
	}

	/**
	 * Set value of ProjectID
	 * @param context
	 * @param projectid
	 */
	public final void setProjectID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String projectid)
	{
		getMendixObject().setValue(context, MemberNames.ProjectID.toString(), projectid);
	}

	/**
	 * @return value of ProjectName
	 */
	public final java.lang.String getProjectName()
	{
		return getProjectName(getContext());
	}

	/**
	 * @param context
	 * @return value of ProjectName
	 */
	public final java.lang.String getProjectName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProjectName.toString());
	}

	/**
	 * Set value of ProjectName
	 * @param projectname
	 */
	public final void setProjectName(java.lang.String projectname)
	{
		setProjectName(getContext(), projectname);
	}

	/**
	 * Set value of ProjectName
	 * @param context
	 * @param projectname
	 */
	public final void setProjectName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String projectname)
	{
		getMendixObject().setValue(context, MemberNames.ProjectName.toString(), projectname);
	}

	/**
	 * @return value of ModelVersion
	 */
	public final java.lang.String getModelVersion()
	{
		return getModelVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelVersion
	 */
	public final java.lang.String getModelVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ModelVersion.toString());
	}

	/**
	 * Set value of ModelVersion
	 * @param modelversion
	 */
	public final void setModelVersion(java.lang.String modelversion)
	{
		setModelVersion(getContext(), modelversion);
	}

	/**
	 * Set value of ModelVersion
	 * @param context
	 * @param modelversion
	 */
	public final void setModelVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String modelversion)
	{
		getMendixObject().setValue(context, MemberNames.ModelVersion.toString(), modelversion);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of AdminUser
	 */
	public final java.lang.String getAdminUser()
	{
		return getAdminUser(getContext());
	}

	/**
	 * @param context
	 * @return value of AdminUser
	 */
	public final java.lang.String getAdminUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AdminUser.toString());
	}

	/**
	 * Set value of AdminUser
	 * @param adminuser
	 */
	public final void setAdminUser(java.lang.String adminuser)
	{
		setAdminUser(getContext(), adminuser);
	}

	/**
	 * Set value of AdminUser
	 * @param context
	 * @param adminuser
	 */
	public final void setAdminUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String adminuser)
	{
		getMendixObject().setValue(context, MemberNames.AdminUser.toString(), adminuser);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return metadataMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final tbncommon.proxies.Metadata that = (tbncommon.proxies.Metadata) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "TBNCommon.Metadata";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
