// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tbncommon.actions;

import java.io.InputStream;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * int getLastRowNum()
 * Gets the last row on the sheet Note: rows which had content before and were set to empty later might still be counted as rows by Excel and Apache POI, so the result of this method will include such rows and thus the returned value might be higher than expected!
 * Returns:
 * last row contained on this sheet (0-based) or -1 if no row exists
 */
public class CountLineFileExcel extends CustomJavaAction<java.lang.Long>
{
	private IMendixObject __ImportExcelDoc;
	private system.proxies.FileDocument ImportExcelDoc;

	public CountLineFileExcel(IContext context, IMendixObject ImportExcelDoc)
	{
		super(context);
		this.__ImportExcelDoc = ImportExcelDoc;
	}

	@java.lang.Override
	public java.lang.Long executeAction() throws Exception
	{
		this.ImportExcelDoc = __ImportExcelDoc == null ? null : system.proxies.FileDocument.initialize(getContext(), __ImportExcelDoc);

		// BEGIN USER CODE
        long line = 0;
		if( this.ImportExcelDoc == null )
			throw new CoreException( "No excel document" );
		
		InputStream content = Core.getFileDocumentContent(this.getContext(),this.ImportExcelDoc.getMendixObject());
		 
		 try  {
			 if (content != null) {
					String fileName = (String) this.ImportExcelDoc.getMendixObject().getValue(this.getContext(), "Name");
					if (fileName != null) {
						int lastdot = fileName.lastIndexOf(".");
						if (lastdot < 0)
							throw new CoreException("Found file has no extension to derive format from.");

						String extension = fileName.substring(lastdot).toLowerCase();

						if (".xlsx".equalsIgnoreCase(extension)) {
							 XSSFWorkbook workbook = new XSSFWorkbook(content);
						     XSSFSheet sheet = workbook.getSheetAt(0);
						     line = sheet.getLastRowNum();	
						}else if (".xls".equalsIgnoreCase(extension)) {
							 HSSFWorkbook workbook = new HSSFWorkbook(content);
							 HSSFSheet sheet = workbook.getSheetAt(0);
							 line = sheet.getLastRowNum();	
					    }else {
							throw new CoreException("The extension: " + extension + " is not supported.");
						}
					}// end if filename
				 }// end if content
		 } catch (Exception e) {
				throw new CoreException(e);
		  } finally {
		        content.close();
		  }
		 
		  return line;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CountLineFileExcel";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
