// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tbncommon.actions;

import java.text.SimpleDateFormat;
import java.util.Locale;
import java.util.TimeZone;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class FormatDateTimeWithLocale extends CustomJavaAction<java.lang.String>
{
	private java.util.Date date;
	private java.lang.String pattern;
	private java.lang.String timeZone;
	private java.util.Date defaultValue;
	private java.lang.String language;
	private java.lang.String country;

	public FormatDateTimeWithLocale(IContext context, java.util.Date date, java.lang.String pattern, java.lang.String timeZone, java.util.Date defaultValue, java.lang.String language, java.lang.String country)
	{
		super(context);
		this.date = date;
		this.pattern = pattern;
		this.timeZone = timeZone;
		this.defaultValue = defaultValue;
		this.language = language;
		this.country = country;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
	    SimpleDateFormat sdf = new SimpleDateFormat(pattern, new Locale(language, country));

	    if (date == null) {
            return sdf.format(defaultValue);
        }
        
        try {
            sdf.setTimeZone(TimeZone.getTimeZone(timeZone));
            return sdf.format(date);
        } catch (Exception e) {
            Core.getLogger(this.getClass().getSimpleName()).warn("Unable to format date " + date, e);
            return sdf.format(defaultValue);
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "FormatDateTimeWithLocale";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
