// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tbncommon.actions;

import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class IsValidDate extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String strDate;
	private java.lang.String format;

	public IsValidDate(IContext context, java.lang.String strDate, java.lang.String format)
	{
		super(context);
		this.strDate = strDate;
		this.format = format;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		 try {
	            DateTimeFormatter formatter = DateTimeFormat.forPattern(format);
	            DateTime d = formatter.parseDateTime(strDate);
	        } catch (Exception e) {
	            return false;
	        }
		  return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "IsValidDate";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
