// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package tbncommon.actions;

import org.apache.commons.lang3.StringUtils;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import tbncommon.actions.MaskUtils;

public class MaskString extends CustomJavaAction<java.lang.String>
{
	private java.lang.String param;
	private java.lang.Long start;
	private java.lang.Long end;
	private java.lang.String mask;

	public MaskString(IContext context, java.lang.String param, java.lang.Long start, java.lang.Long end, java.lang.String mask)
	{
		super(context);
		this.param = param;
		this.start = start;
		this.end = end;
		this.mask = mask;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
	    try
        {
	        if (StringUtils.isBlank(mask))
	            throw new NullPointerException("Mask should not be null.");
	            
            return MaskUtils.maskString(param, start.intValue(), end.intValue(), mask.charAt(0));
        }
        catch (Exception e)
        {
            throw new com.mendix.systemwideinterfaces.MendixRuntimeException(e);
        }
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "MaskString";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
